### ISSUE TITLE
laravel.log: Permission denied.

### ISSUE THREAD

**Issue by faasie** [shipping-docker/vessel#1]
On first install, after vessel start.

Visiting `http://localhost`

Immediately get Whoops error:
```
The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
```

OpenSUSE 42.3
Docker version 17.04.0-ce, build 78d1802
ZSH shell

I know it's newly released. Just a quick observation.

Edit:
Connecting to `app` container:
`./vessel exec app bash`

and then manually running:
`chown -R www-data: /var/www/html`

Resolves this issue. Not sure it's not running from the dockerfile.

**Comment by fideloper** [comment]
It's actually not released yet at all!

I need to sort out permissions on Linux hosts, just haven't gotten that in
place yet.

Thanks

**Comment by faasie** [comment]
@fideloper ....My BAD! :-/

I guess I read you saying "check it out" and figured it may have been partially released!

I'm still very much looking forward to playing with this but will wait for an official release!

👍

**Comment by fideloper** [comment]
No problem!

I have some work towards this on the linuxperms branch but need to finish
testing some NodeJS stuff.

**Comment by lkmadushan** [comment]
@fideloper What do you think about passing current `UID` and `GID` to Dockerfile through `Vessel` script file.

Vessel file
```
export PUID=$(id -u `whoami`)
export PGID=$(id -g `whoami`)

# Users of the docker containers
DOCKER_USER_APP="www-data"
DOCKER_USER_NODE="node"
```

So we can pass the use to compose command..
```
$COMPOSE run --user="$DOCKER_USER_APP" --rm $TTY \
            -w /var/www/html \
            app \
            composer "$@"
```

Dockerfile
```
# Set permissions
ARG PUID=33
ARG PGID=33
RUN groupmod -g $PGID www-data \
    && usermod -u $PUID www-data

RUN chown -R www-data:www-data /var/www
RUN chmod 755 /var/www
```

**Comment by fideloper** [comment]
Hi @lkmadushan - thanks!

I'm currently doing that for the [Node container](https://github.com/shipping-docker/vessel/blob/linuxperms/docker-files/docker/node/Dockerfile#L3-L4), although I haven't finished testing it, but I think that will get us where we need to be.

I'm doing similar for the `app` container, however I'm not doing that at build-time with the `Dockerfile`, but instead I'm doing it [when the container spins up dynamically](https://github.com/shipping-docker/vessel/blob/linuxperms/docker-files/docker/app/start-container#L13-L15).

See the commits on the https://github.com/shipping-docker/vessel/tree/linuxperms branch to see more.

I may make this consistent to do the same way on each (Node and App images/containers). The only thing I don't like about the Dockerfile is the UID/GID gets hard-coded. However that's *probably* not an issue for more people using this on their dev machine. So, I think we'll likely end up going with your suggestion, but I want to play with it more to make sure it's a solid way to go about it.

Thanks again!

**Comment by lkmadushan** [comment]
@fideloper you're welcome.

I like the idea of changing the user when the container spins up. need to check that out :)

Really enjoyed your shipping docker course and learned a lot from it. I was waiting for another episode that contains using docker in production with `rancheros`.

Thank you very much for sharing knowledge with others.

FYI: I had an issue when I'm using current user's UID/GID of host machine to fix linux permission, it's already allocated for an another application in the container.

**Comment by fideloper** [comment]
PR #3 should settle this.

**Comment by dbpolito** [comment]
> PR #3 should settle this.

This fixes this problem when php-fpm generates the file, but when you to `vessel art make:...` or an artisan command generates the log file, it still gets permission problems, right?

I think it still needs what you did on node regarding to UID.

**Comment by fideloper** [comment]
Hmmm I'll check it out - it's possible that CLI-run php is still being run
as user root instead of the correct user. Thanks!

**Comment by vedmant** [comment]
I just installed vessel and have this problem from the first run, also it's not mapping ports to localhost (Mac Os).

**Comment by fideloper** [comment]
@vedmant The latest release should resolve that, however you'll need to [rebuild your images](https://vessel.shippingdocker.com/docs/updating-resetting/) if you previously installed Vessel.

Also, the docs say what is likely happening on localhost, but I won't know without you letting us know what error output you get, if any. You likely have the EADDRINUSE issue: https://vessel.shippingdocker.com/docs/common-issues/#eaddrinuse

**Comment by faasie** [comment]
@vedmant  and @fideloper, I haven't seen this issue since the latest update, as Chris said. I have been using it non-stop since updating and rebuilding the boxes. It's a beautiful project!

**Comment by vedmant** [comment]
Composer installed version "1.1.3", that's latest, according to releases list. No, I don't have any EADDRINUSE issues, it's not important, I open my app on "http://192.168.99.100/". Just tried to delete and reinstall everything, according to instructions, have the same error: "The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied".

**Comment by fideloper** [comment]
Gotcha - Any reason not to use `localhost`? Sounds like if that doesn't work, something else might be going on (perhaps `localhost` is changed to something else in your `/etc/hosts` file, or maybe `localhost` is bound to port 80 but your 192.*.*.* network is not).

I've never had a permission issue in MacOS, Docker for Mac tends to make that Just Work™ since it works within a virtualized layer. Something on your system is different but I'm not sure what. Note that the version of Docker will matter more than the version of Docker-Compose.

Here's what I'm using:

Head to About Docker in this menu:

![image](https://user-images.githubusercontent.com/467411/32275839-b8eb4c8c-beda-11e7-895d-219c4c856973.png)

And see if perhaps you're on an older version of Docker?

![image](https://user-images.githubusercontent.com/467411/32275828-ae59142a-beda-11e7-9ed9-4eda4def9acf.png)

**Comment by fideloper** [comment]
@vedmant should also note that if you're not using Docker for Mac, and are instead using something like Docker Toolbox (running Docker within a virtualbox vm), then you'll run into errors like this, as the user ID it's attempting to run commands as may not match up to the user owning the files within the virtualbox VM. Vessel just won't work properly using Docker Toolbox (or while running Docker through a VM and using docker-machine to control it).

**Comment by vedmant** [comment]
Thanks a lot, I think I installed docker somehow differently, yes, it's running on my Virtualbox and instead of Docker.app I have folder "Docker" in Applications with "Docker Quickstart Terminal" and "Kitematic (Beta)". I'll reinstall Docker completely.

**Comment by fideloper** [comment]
Ah ha, that'll definitely do it! The "Docker for Mac" installer is a newer way they have to install it that should work better overall if you're able to try it out! https://docs.docker.com/docker-for-mac/install/

**Comment by farmercode** [comment]
我也遇到类似的问题！不过我的做法是根据将容器内部的www-data用户和组的id改为一致，然后容器以www-data的身份运行。这时挂载就没有问题了啊！这是我自己做的[php镜像](https://github.com/farmercode/php72)，希望对遇到同样问题的朋友有帮助。

**Comment by farmercode** [comment]
我也遇到类似的问题！不过我的做法是根据将容器内部和外部的www-data用户和组的id改为一致，然后容器以www-data的身份运行。这时挂载就没有问题了啊！这是我自己做的[php镜像](https://github.com/farmercode/php72)，希望对遇到同样问题的朋友有帮助。

**Comment by colynb** [comment]
Ok, I'm also having this issue and yes, I'm running vessel through docker-machine. Any advice on what to do?
