### ISSUE TITLE
Upgrade giving bad gateway

### ISSUE THREAD

**Issue by Jamesking56** [shipping-docker/vessel#100]
## Description

Upgrading from Vessel 3.2.0 -> 4.0.0 is now giving me a Bad Gateway error when viewing my Laravel 5.5 app.

## OS

My OS is:

- [x] MacOS [**Choose one:** High Sierra]
- [x] Linux
- [ ] Windows

## Docker

The output of `docker version`:

<details>
<summary>macOS (docker machine using dinghy)</summary>

```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.4
 Git commit:        4c52b90
 Built:             Thu Jan 10 03:22:19 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:57 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
</details>

<details>
<summary>Ubuntu 18.04</summary>

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
</details>

---
The output of `docker-compose version`:

<details>
<summary>macOS (docker machine using dinghy)</summary>

```
docker-compose version 1.23.2, build unknown
docker-py version: 3.6.0
CPython version: 3.7.2
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```
</details>

<details>
<summary>Ubuntu 18.04 LTS</summary>

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
</details>

**Comment by Jamesking56** [comment]
This is also coming from `laravel.log`:

```
local.ERROR: Unsupported operand types {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Unsupported operand types at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Arr.php:219)
```

**Comment by fideloper** [comment]
Hi! See issue #97 for an explanation.

**Comment by Jamesking56** [comment]
Yep I just added a line right before `ENTRYPOINT` in the `docker/app/Dockerfile`:

```
RUN rm /etc/php/7.3/fpm/conf.d/20-xdebug.ini
```

Ear-marked this line to review at a later date, when xdebug is fixed.

Keep up the good work @fideloper :+1:

**Comment by fideloper** [comment]
Great - thanks!

**Comment by Jamesking56** [comment]
@fideloper has it been fixed? https://github.com/xdebug/xdebug/pull/438

**Comment by fideloper** [comment]
Not sure!

It relies on:

1. https://github.com/xdebug/xdebug/releases (maybe?) - if these releases are used or if it's just using the master branch
2. https://launchpad.net/~ondrej/+archive/ubuntu/php - If this repository maintainer has rebuilt the PHP module with this xdebug bug fix

**Comment by Jamesking56** [comment]
If you didn't know, it seems to have released: https://xdebug.org/updates.php
