### ISSUE TITLE
Empty folder when using WSL

### ISSUE THREAD

**Issue by ow** [shipping-docker/vessel#105]
## Description
I've followed all of the config steps to use Vessel, and successfully run my project on a macOS machine. With a WSL/Windows 10 box, however, everything works as planned _except_ my application isn't mounted into the Docker box. I can't quite figure out why - there are no errors, it's just as if it never even tried to mount. This means all commands like `vessel composer install` come back with "no files found" or that composer.json is missing.

I'm trying to figure out the magic incantations Windows might need to make this work. As far as I can see from the issue/commit history, WSL is supported, but it's unclear if I need to change the default config to allow it to function properly.

## OS

My OS is:

- [ ] MacOS [**Choose one:** Yosemite, El Capitan, Sierra, High Sierra, Mojave]
- [ ] Linux
- [x] Windows 10 (1809/17763, non-insider build, stable branch)

## Docker

The output of `docker version`: 

```
Docker version 18.06.1-ce, build e68fc7a
```

The output of `docker-compose version`:

```
docker-compose version 1.17.1
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Comment by fideloper** [comment]
Hi!

Check this out on setting up Windows with WSL - https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

It looks like the docker-compose file with Vessel may need adjustments for the file path used for mounting.

**Comment by ow** [comment]
Aha! Thanks for this - I didn't see anything about this in the documentation so it might be worth me making a PR to clarify that :)
