### ISSUE TITLE
Proposal:  Add `help` output

### ISSUE THREAD

**Issue by mikeerickson** [shipping-docker/vessel#106]
Hey @fideloper 

I am curious if you are keen on accepting a PR to add help output

```
> vessel --help, -H
```

I often forget what commands are available when I am using across projects, thinking it would be nice to have internal help system

**Comment by fideloper** [comment]
If you have the time, that’d be great!

**Comment by mikeerickson** [comment]
I do, and I will 🤓

I will have it ready Monday, maybe sooner 👍

**Comment by mikeerickson** [comment]
@fideloper How about including a version report as well.  The only place I can find any version information is here is on Packagist (so far as I can tell, the latest version is 4.0.1)

Where do you manage the versions, have they just tagged releases only, I don't see any version information in the vessel bash script?

**Comment by mikeerickson** [comment]
@fideloper I have added this to the current script so the version can be tracked moving forward

```
...
line 3:  VERSION="4.0.2" # new variable, bumped to support vessel --help
...
```

I am going to move forward with this, unless you would rather me not included along with the `--help` implementation

**Comment by mikeerickson** [comment]
@fideloper OK, all done... Here are help and version screenshots. Let me know if you have any comments, if all good, I will submit PR

Help is invoked by

```bash
$ vessel --help
$ vessel -H
$ vessel help
```

### Help Screen
![image](https://user-images.githubusercontent.com/183153/54498018-d3729a00-48be-11e9-94aa-2cccecf83acc.png)

```bash
$ vessel --version
$ vessel -v
$ vessel version
```
### Version Screen
![image](https://user-images.githubusercontent.com/183153/54498034-f43aef80-48be-11e9-9f53-856ff4f8cbf9.png)

**Comment by fideloper** [comment]
That looks nice, thanks!

The version is just the github tags, correct. I don't have an issue with also having that as part of the help menu, however. I'll probably write a quick bash script to automate releases to update that at the same time or something 👍

**Comment by mikeerickson** [comment]
I will PR this part of work, then create separate PR to create bash deployment script etc

**Comment by mikeerickson** [comment]
@fideloper 

I have added PR -- https://github.com/shipping-docker/vessel/pull/107

**Comment by fideloper** [comment]
Thanks, I’ll take a look soon!
