### ISSUE TITLE
Unable to use mysql

### ISSUE THREAD

**Issue by bistory** [shipping-docker/vessel#110]
## Description

I freshly installed docker and Vessel on my working station. But when trying to migrate my database, I get an error :

```
Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select * from information_schema.tables where table_schema = laravel and table_name = migrations and table_type = 'BASE TABLE')
```

And when running

```
# Log into mysql
./vessel mysql
```

I get this message : ERROR: No container found for mysql_1

Thanks for your help !

## OS

My OS is:

- [x] MacOS [Mojave]
- [ ] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

The output of `docker-compose version`:

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

The output of `docker image ls`:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vessel/node         latest              3e98f69e6c95        About an hour ago   928MB
vessel/app          latest              cf10e96ea585        About an hour ago   355MB
node                latest              b074182f4154        6 hours ago         906MB
mysql               5.7                 a1aa4f76fab9        15 hours ago        373MB
redis               alpine              72e76053ebb7        3 weeks ago         50.9MB
ubuntu              18.04               7698f282e524        3 weeks ago         69.9MB
```

**Comment by fideloper** [comment]
Hi!

What command did you use to migrate? You'll need to run `./vessel art migrate` in order for the `app` container to talk to the `mysql` container successfully (running `php artisan migrate` from your host machine won't work, as your host machine doesn't know the address of the `mysql` container).

Restarting  Vessel may clear it, but I'll need some extra info to see what may have happened:

```bash
# Make sure everything's off
./vessel down

# Restart everything
./vessel start

# Wait a few seconds for everything to spin up, then

# See what's running...
./vessel ps

# And we'll get log output from mysql to see if there's an error
./vessel logs mysql
```

Let me know what you see!

**Comment by bistory** [comment]
Thanks, I fixed the first problem by setting a password (duh...) but now I'm stuck still when trying to migrate but with an other error ;

```
mysql_1  | MySQL init process in progress...
mysql_1  | 2019-06-12T12:33:18.907655Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1  | 2019-06-12T12:33:18.909188Z 0 [Note] mysqld (mysqld 5.7.26) starting as process 89 ...
mysql_1  | 2019-06-12T12:33:18.913917Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1  | 2019-06-12T12:33:18.914293Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1  | 2019-06-12T12:33:18.916945Z 0 [Note] InnoDB: Uses event mutexes
mysql_1  | 2019-06-12T12:33:18.917034Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1  | 2019-06-12T12:33:18.917112Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1  | 2019-06-12T12:33:18.917206Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1  | 2019-06-12T12:33:18.917557Z 0 [Note] InnoDB: Number of pools: 1
mysql_1  | 2019-06-12T12:33:18.918052Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1  | 2019-06-12T12:33:18.921422Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
mysql_1  | 2019-06-12T12:33:18.933169Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1  | 2019-06-12T12:33:18.936506Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1  | 2019-06-12T12:33:18.950210Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1  | 2019-06-12T12:33:18.972220Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1  | 2019-06-12T12:33:18.972582Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1  | 2019-06-12T12:33:19.041019Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1  | 2019-06-12T12:33:19.042404Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1  | 2019-06-12T12:33:19.042554Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1  | 2019-06-12T12:33:19.043111Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1  | 2019-06-12T12:33:19.094165Z 0 [Note] InnoDB: 5.7.26 started; log sequence number 2524985
mysql_1  | 2019-06-12T12:33:19.095060Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1  | 2019-06-12T12:33:19.095496Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1  | 2019-06-12T12:33:19.103135Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1  | 2019-06-12T12:33:19.103973Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190612 12:33:19
mysql_1  | 2019-06-12T12:33:19.106860Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1  | 2019-06-12T12:33:19.124402Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql_1  | 2019-06-12T12:33:19.139254Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1  | 2019-06-12T12:33:19.141232Z 0 [Note] mysqld: ready for connections.
mysql_1  | Version: '5.7.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
mysql_1  | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'
```

**Comment by fideloper** [comment]
Hmmmmmm, I'll need to know exactly what commands you're running and how to really know what's going on. I haven't run into this before. Perhaps some environment variables are missing? 

The `.env` file (I'm assuming a Laravel application) is shared by both Vessel and Laravel. There are defaults in Vessel if it doesn't find a value but perhaps something in your `.env` file is causing an empty password where one can't be used or something like that.

In any case, let me know exactly what steps you took and I perhaps can recreate it or point something out.

**Comment by bistory** [comment]
Strange, I did nothing special, I installed Docker, then created a git, laravel new and followed the install procedure here : https://vessel.shippingdocker.com/docs/get-started/

I already tried to clear everything Docker related to be sure nothing is breaking there...

Here is my env file ;

```
APP_NAME=SoPRISM
APP_ENV=local
APP_KEY=base64:doYRJWkMpGE7utJ/RFmSiNiUagXjMaeXVPelwTL8IMQ=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_CONNECTION=sync
SESSION_DRIVER=redis
SESSION_LIFETIME=120

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
```

**Comment by fideloper** [comment]
Ah, I think I see the issue - Use another user other than “root” in your
.env file.


In your case,  run “./vessel down -v” (or follow the docs on resetting
Vessel) before restarting vessel with the updated .env file.

The key there is deleting the volumes (the mysql data) so it re-creates the
new users based on the updated .env file when you start vessel back up.
MySQL only creates the users the first time its spun up and sees theres no
data initialized yet.

**Comment by bistory** [comment]
Thanks ! It worked ^^
I think I tested a username different than root, but without a password, I never tested username + password...

**Comment by fideloper** [comment]
Gotcha! I'll make a note of that to improve the docs there. Those are both a result of how the MySQL container expects to have settings set when it's created the first time and setting passwords.

**Comment by madsem** [comment]
I actually just ran into the same issue, wouldn't it be cool if vessel adjusts the `DB_USERNAME` also automagically?

**Comment by madsem** [comment]
I actually commented to soon, it seems it's not just the DB_USERNAME but password also need to be set?

```
> vessel stop
Stopping ppc-optimizer_redis_1 ... done
Stopping ppc-optimizer_app_1   ... done
Removing ppc-optimizer_node_1  ... done
Removing ppc-optimizer_redis_1 ... done
Removing ppc-optimizer_app_1   ... done
Removing ppc-optimizer_mysql_1 ... done
Removing network ppc-optimizer_vessel
> vessel start
Creating network "ppc-optimizer_vessel" with driver "bridge"
Creating ppc-optimizer_mysql_1 ... done
Creating ppc-optimizer_node_1  ... done
Creating ppc-optimizer_app_1   ... done
Creating ppc-optimizer_redis_1 ... done
> vessel ps
        Name                      Command             State          Ports
---------------------------------------------------------------------------------
ppc-optimizer_app_1     start-container               Up       0.0.0.0:80->80/tcp
ppc-optimizer_mysql_1   docker-entrypoint.sh mysqld   Exit 1
ppc-optimizer_node_1    docker-entrypoint.sh node     Exit 0
ppc-optimizer_redis_1   docker-entrypoint.sh redis    Up       6379/tcp
                        ...
> vessel logs mysql
Attaching to ppc-optimizer_mysql_1
mysql_1  | error: database is uninitialized and password option is not specified
mysql_1  |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

**Comment by fideloper** [comment]
Hi!

Semi-recently we added the "allow empty passwords" option to the
docker-compose file to allow empty passwords:
https://github.com/shipping-docker/vessel/blob/master/docker-files/docker-compose.yml#L39

If you don't have that in your current docker-compose file, you can add it
in and then start your containers again. You may need to delete your MySQL
volume related to that project there to make MySQL re-initialize itself
when you start it back up.

(You can see your created volumes using the "docker volume ls" command, and
remove one via "docker volume rm <volume_id_or_name>").

**Comment by madsem** [comment]
Hey @fideloper , I think there is some kind of bug with the empty mysql password option.
I've updated vessel to 5.0.0 and then reset vessel completely to make use of the no password option.

After that I wasn't able to connect anymore.

It was actually super weird, I was able to migrate the database tables, rollback etc but whenever I tried to make an Eloquent query I've had the `Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] php_network_getaddresses` error thrown at me.

Now I've reverted everything back to using a password, and things work again.

I'm unsure, was there any other step I would have needed to take to make it work, besides updating to 5.0.0 and then reseting vessel and adjusting my .env?

**Comment by fideloper** [comment]
Hi!
Are you sure you reset everything completely? If you did not remove the docker volumes associated, then the old data may still be there, including the users.

For the error `php_network_getaddresses`, that would mean the hostname was not responding (the hostname in this case is `mysql`). In that case I suspect either the mysql container wasn't running yet, or you ran the command outside of `./vessel...` locally on your machine.

But let me know either way!

**Comment by madsem** [comment]
Hey thanks for the quick reply!

First time when I updated to the latest vessel, I've follwed these steps:
https://vessel.shippingdocker.com/docs/updating-resetting/

Here is what I did now (And realized eloquent queries actually still don't work and throw the `php_network_getaddresses` error, but running `vessel art migrate` works!!!):

```shell
# i've aliased ./vessel to vessel
$ vessel down
$ docker volume ls
$ docker volume rm <volume>
$ vessel start
```

I'm running all artisan commands through vessel

**Comment by madsem** [comment]
@fideloper so sorry, it all works as expected also without password. I should not blindly use the cli history or maybe not even try to code when having a cold... I literally did not see that in my history it was using `php` instead of `vessel`, for 2 hours... I feel like an idiot :) Sorry for the inconvenience

**Comment by fideloper** [comment]
haha, no problem! I’ve done it myself plenty of times :D

Glad you caught that!

**Comment by r0gu30n3** [comment]
hi  I have the same problem my exits are the following
$ ./vessel start
Creating network "my-app_vessel" with driver "bridge"
Creating my-app_redis_1 ... done
Creating my-app_node_1  ... done
Creating my-app_mysql_1 ... done
Creating my-app_app_1   ... done

./vessel ps
     Name                  Command             State               Ports           
-----------------------------------------------------------------------------------
my-app_app_1     start-container               Up       0.0.0.0:80->80/tcp,:::80->8
                                                        0/tcp                      
my-app_mysql_1   docker-entrypoint.sh mysqld   Exit 1                              
my-app_node_1    docker-entrypoint.sh node     Exit 0                              
my-app_redis_1   docker-entrypoint.sh redis    Up       6379/tcp 

./vessel logs mysql
Attaching to my-app_mysql_1
mysql_1  | 2021-06-03 15:35:41+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.34-1debian10 started.
mysql_1  | 2021-06-03 15:35:41+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1  | 2021-06-03 15:35:41+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.34-1debian10 started.
mysql_1  | 2021-06-03 15:35:41+00:00 [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user
mysql_1  |     Remove MYSQL_USER="root" and use one of the following to control the root user password:
mysql_1  |     - MYSQL_ROOT_PASSWORD
mysql_1  |     - MYSQL_ALLOW_EMPTY_PASSWORD
mysql_1  |     - MYSQL_RANDOM_ROOT_PASSWORD

and the passwords are empty
