### ISSUE TITLE
Vessel at production

### ISSUE THREAD

**Issue by xerod** [shipping-docker/vessel#111]
I'm new to docker and I assume that the docs are written for local development only. It will be nice if the docs tells us the easy way to use it at production since vessel is so easy to set-up.

Thank you

**Comment by fideloper** [comment]
Hi!

Unfortunately if it was suitable for production, it wouldn't be easy anymore! This is *mostly* said with some sarcasm but is.....not too far from the truth. Docker in production tends to be pretty complicated.

I have a course [Shipping Docker](https://serversforhackers.com/shipping-docker) that gets into it (starts basic and builds up).  You can also check out some videos here (free) to get a feel for Docker some more: https://serversforhackers.com/t/containers
