### ISSUE TITLE
MySQL 8 Support

### ISSUE THREAD

**Issue by djam90** [shipping-docker/vessel#118]
## Description
It would be great if Vessel supported MySQL 8.

## OS

My OS is:

- [ ] MacOS [**Choose one:** Yosemite, El Capitan, Sierra, High Sierra, Mojave]
- [x] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

The output of `docker-compose version`:

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

```

**Comment by fideloper** [comment]
Hello!

This will eventually happen, but I'm going to leave 5.7 the default for now.

If you want version 8, do the following:

1. In your `docker-compose.yml` file, change `mysql:5.7` to `mysql:8`
2. [Optional but very much recommended], add a `command:` within the `mysql` service  with the following: `command: "--default-authentication-plugin=mysql_native_password"`

The 2nd item there prevents some issues with how MySQL 8 handles authentication.

The docker-compose section for `mysql` will look something like this:

![image](https://user-images.githubusercontent.com/467411/64359132-5e5e6280-cfcd-11e9-9cef-5b025272e65b.png)
