### ISSUE TITLE
Feature Request: Hyper.sh integration (or similar)

### ISSUE THREAD

**Issue by jm-mwi** [shipping-docker/vessel#12]
It would be amazing if there could be some form of integration with a pure container service like [hyper.sh](hyper.sh)! If there is alternative that would work too!

Basically, just some option that would allow pushing a local container to a production environment.

**Comment by fideloper** [comment]
Hi!

I'm not really clear on if they have their own dev environment you can use or not. However I probably don't want to integrate any specific (paid) platforms.

If you know how to use it, and can write up an example, I can play with that and add it to the Customizing Vessel docs.
