### ISSUE TITLE
Artisan Confirm/Ask Skipped

### ISSUE THREAD

**Issue by rabrowne85** [shipping-docker/vessel#122]
## Description
If an artisan command makes use of the `confirm()` or `ask()` function then the vessel environment doesn't allow the user to make the confirmation or provide any input. The default option is used or no input in the case of `ask()`.

I've tested this on both MacOSX and Ubuntu Linux distros and the issue is present in both.

I can't seem to find any reference to anyone else having this issue, or any solutions.

## OS

My OS is:

- [x] MacOS [Mojave]
- [x] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfca03
 Built:             Thu Aug 29 05:29:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfca03
  Built:            Thu Aug 29 05:27:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

The output of `docker-compose version`:

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by fideloper** [comment]
Is this when running commands like `./vessel art some:thing` ? (what commands are you running exactly?)

I've never had an issue with adding input, so I'm curious about what's going on there.

Try this out and see what happens:

```bash
# "log into" the container
./vessel exec app bash

# If you're not in your project dir, cd into /var/www/html
# However you should be in the correct place when logging in
cd /var/www/html

# Try running a command "normally" to see
# if it is interactive or not
php artisan foo:bar
cd /var/www/html
```

In terms of using docker, this sounds like `-it` is't being used (allowing prompts into docker to be interactive / assigning a pseudo-tty).

Please let me know:

1. Exactly what commands you were running for this behavior
2. What happens when attempting the above!

**Comment by rabrowne85** [comment]
@fideloper you're spot on; the `-it` was missing from the vessel config for artisan commands. Not sure when that happened but that's what the problem was.

Thanks for the hint.

**Comment by fideloper** [comment]
You mean like that needs to be fixed, or did you have an older version of vessel?

Note that most commands use `docker-compose` under the hood, where `-it` flags are used by default (which `docker-compose` does, rather than a thing Vessel sets up itself).
