### ISSUE TITLE
US Locales are not supported

### ISSUE THREAD

**Issue by colynb** [shipping-docker/vessel#126]
## Description

I'm switching from Homestead to Vessel and I'm unable to get locales to work as expected in the new docker containers. The vagrant machine built with homestead doesn't have this problem. I have an app with a bunch of tests for formatting money and they are all failing.

## OS

My OS is:

- [ X] MacOS [**Choose one:** Yosemite, El Capitan, Sierra, High Sierra, Mojave]
- [ ] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

The output of `docker-compose version`:

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.5.0
CPython version: 2.7.16
OpenSSL version: LibreSSL 2.8.3
```

**Comment by fideloper** [comment]
Hello!

The container doesn't have most locales installed (one of the steps the base Ubuntu container takes to make the container as small as possible). 

What you can do is edit your Vessel `Dockerfile` (`docker/app/Dockerfile`) and install the `locales` packages (`apt-get install -y locales`). The easiest way is likely to add the `locales` package in the list of installed packages in the same line as `apt-get install -y curl zip unzip git supervisor sqlite3`.

Then you may want to run some commands to setup the locale you want. Here's an example of someone setting up an Australian locale: https://docs.chipperci.com/builds/environment/#sudo

(You can add additional commands to your Dockerfile within a `RUN` stanza, or you can run these commands in your container if you need to change locales on the fly).

After updating your Dockerfile, you can [rebuild your Vessel image](https://vessel.shippingdocker.com/docs/updating-resetting/#resetting) to incorporate those changes.
