### ISSUE TITLE
Change node version ?

### ISSUE THREAD

**Issue by uar-daniel-gafitescu** [shipping-docker/vessel#128]
## Is there a way to change the node version ?
I have install via npm `n` but I can not manage to change the node version.
Is there anyway you can do that since I can not bash into the image or ssh in ?

**Comment by fideloper** [comment]
Hi!

I think the change to make this happen would be a bit complicated.

What's your use case? Do you just need a specific node version for a
project, or do you need to change node versions within a project that uses
Vessel?

**Comment by SampsonCrowley** [comment]
@fideloper there would be lots of reasons why a specific NPM or Node version is needed. there are quite a few libraries that aren't able to support the latest and greatest version right away, and plenty of legacy code out in the wild that still relies on some older versions, like node-sass and laravel-elixir
