### ISSUE TITLE
Feature Request: Integrate Mutagen for better I/O on MacOs

### ISSUE THREAD

**Issue by nirajhinge** [shipping-docker/vessel#134]
## Description

I am trying to integrate [Mutagen](https://mutagen.io/) with the Vessel as the docker performance on my MacOS is rather slow. I know this is not particularly a Vessel specific issue but with Mutagen, there seems to be a possibility to resolve this as these folks have done for [Magento Dev environment](https://github.com/mage2click/m2c). I have got a preliminary setup that doesn't seem to be improving the performance but my knowledge of the whole setup is a weak so I was wondering if there was any chance of trying integrating it into this Vessel as an option? 

I have a [ticket](https://github.com/mutagen-io/mutagen/issues/188) created in mutagen discussing the issue I was having. There are some examples config files in the issue. Thanks.

## OS

My OS is:

-  MacOS (Catalina)

## Docker

The output of `docker version`: 

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

The output of `docker-compose version`:

```
docker-compose version 1.25.2, build 698e2846
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

**Comment by fideloper** [comment]
Really sorry, but I don't think I have the bandwidth to look into this any further than you have with the issue open in Mutagen's  repository :/
