### ISSUE TITLE
Feature Request: Switch to MariaDB

### ISSUE THREAD

**Issue by jm-mwi** [shipping-docker/vessel#14]
This is small so feel free to close, but it would be handy if this used MariaDB by default. From looking at stats online until you get into the range of massive amounts of cores MariaDB seems to perform better.  This change would, in theory, be pretty simple to make.

If there is interest here this is a change I'd consider spending time on if I can find some.

**Comment by fideloper** [comment]
It is simple to make that change, yep!

I’m gonna keep using mysql for now on Vessel, but if you want to change it
to MariaDB, check out the example on the docs under “Customizing Vessel”
linked below.

The docs show swapping to pgsql, but you can swap it with mariadb super
easily in your own installs (probably easier than changing to pgsql, I
believe it uses the exact same environment variables)

https://vessel.shippingdocker.com/docs/customizing-vessel/#pgsql

**Comment by mikeerickson** [comment]
@fideloper I agree with you, stick to the core and let devs extend as needed.  This is a problem with @lararock (way too many options and makes for painful support)
