### ISSUE TITLE
vessel art make:something always hangs for a while before returning

### ISSUE THREAD

**Issue by madsem** [shipping-docker/vessel#145]
## Description

Running the latest vessel, composer required today. Whenever I run `vessel art make:model Something -mf` the command pretty much instantly outputs that model was created, but then kind of spins/hangs for up to one minute before the command line is usable again for new input.

Unsure what I can do to fix this, or if that is even Vessel/Docker or my machine (Macbook Pro 15" late 2019)

## OS

My OS is:

- [*] MacOS [Catalina]
- [ ] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

```
➜ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

The output of `docker-compose version`:

```
➜ docker-compose version
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by fideloper** [comment]
I can't really reproduce this one. Any idea if a good old fashioned restart would resolve this?
