### ISSUE TITLE
Laravel 7 error "Please make sure the PHP Redis extension is installed and enabled."

### ISSUE THREAD

**Issue by viglucci** [shipping-docker/vessel#150]
## Description

Not really sure what happened but I was able to run my Laravel 7 application just fine until I tried to upgrade to the latest vessel, and now I get an error on every request:

```
Please make sure the PHP Redis extension is installed and enabled.
```

The very confusing bit is that even if I revert the repository to the state it was in before I tried to update vessel I get the same issue... Should the Docker image not have all the needed extensions to run a Laravel 7 app by default?

A workaround is to just not use the Redis drivers for cache or session, but since vessel comes with a Redis container I assume it would be ready to go, and that was indeed the case when I originally added vessel to the project.

## OS

My OS is:

- [ ] MacOS [**Choose one:** Yosemite, El Capitan, Sierra, High Sierra, Mojave]
- [ ] Linux
- [x] Windows

## Docker

The output of `docker version`: 

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

The output of `docker-compose version`:

```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by ibnumalik** [comment]
you need to put this in the env file

```
REDIS_CLIENT=predis
```

or update related configuration to use predis

**Comment by viglucci** [comment]
Using `predis` instead of `phpredis` fixes this, as suggested (https://github.com/shipping-docker/vessel/issues/150#issuecomment-893085642). I am confused why the default `phpredis` doesn't work out of the box though, since it appears that `php-redis` is installed as a module in the Dockerfile.
