### ISSUE TITLE
Ambiguous ERROR: Unable to find 'docker' 

### ISSUE THREAD

**Issue by VencaCZ** [shipping-docker/vessel#156]
## Description

When running initial setup it will fail on "chown: invalid user: ‘user:user’"

## OS

My OS is:

- [ Ubuntu 22.04 ] Linux

## Docker

The output of `docker version`: 

```
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
```

The output of `docker-compose version`:

```
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
```
o3tanks.sh line 438

```
if ! [ -S "${docker_socket}" ]; then
        docker_socket="/run/docker.sock"

        if ! [ -S "${docker_socket}" ]; then
                throw_error "${MESSAGES_MISSING_DOCKER}"
        fi
fi
```

There should be different message when there is issue with docker_socket and not ERROR: Unable to find 'docker' 
This error will confuse user into thinking that their is problem with their docker installation instead of checking if they have docker running

**Comment by VencaCZ** [comment]
As a side note (Not sure if its worth another issue its still same part of the code) docker_socket can be in another place in system. Instead of using hardcoded location it should check docker service and see if its running and if yes where the sock file is located (If you need it for any other purposes)

**Comment by fideloper** [comment]
Hi! I don’t really maintain this much anymore - since Laravel Sail exists
now.

Have you checked that out?

**Comment by VencaCZ** [comment]
It does not change, that there is issue and it should be reported. Even when it is not maintained

**Comment by VencaCZ** [comment]
Looks like issue was posted in wrong project somehow? Ignore and close it.
