### ISSUE TITLE
All Artisan arguments not passed through

### ISSUE THREAD

**Issue by tymondesigns** [shipping-docker/vessel#18]
Hi mate.. Great job on the package

When I run something like `./vessel artisan preset none`

It seems like the last argument is not being passed through as seen here

![image](https://user-images.githubusercontent.com/1801923/31836953-f635cb54-b5ce-11e7-8cfd-2ecf5011abd8.png)

This obviously works when running `php artisan preset none` on the host.

And other single argument commands work as expected such as `./vessel artisan horizon`

Am I doing something wrong here?

Cheers

EDIT: it's weird that this doesn't work since you use `php artisan "$@"` in the bash script... confused lol

**Comment by fideloper** [comment]
Hi! I’ve passed many arguments through I believe - can you see if it’s
other commands or just this one? Perhaps there’s something special about
using “none”

Is they command specific to you’re laravel app? I don’t remember if the
preset command is an out of the box command or not.

Thanks!

**Comment by tymondesigns** [comment]
Yea the command is a [native Laravel one](https://laravel.com/docs/5.5/frontend#introduction)

It is kind of weird that it doesn't fit with all the other commands that are separated by a colon (All of those seem to work by the way)

I can't think of another command that has a separate argument

![image](https://user-images.githubusercontent.com/1801923/31838648-ada5b1fe-b5d5-11e7-854d-6ccf7512208c.png)

**Comment by fideloper** [comment]
Gotcha - I’ll check it out soon and see if I can find a reason - thanks!

**Comment by tymondesigns** [comment]
I've found the problem line

it's here:
![image](https://user-images.githubusercontent.com/1801923/31839715-39af4698-b5da-11e7-9313-4a91778c46b5.png)

As you can see when I shutdown the containers, it works as expected!

![image](https://user-images.githubusercontent.com/1801923/31839697-2b4b6dca-b5da-11e7-8343-d5392a2428d3.png)

I'm not skilled enough at bash to fix it though 😄

**Comment by tymondesigns** [comment]
Actually PR #19 fixes the issue

**Comment by fideloper** [comment]
Fixed in https://github.com/shipping-docker/vessel/commit/d8b90265a6119cb4d2cdc0729db22264f89990da. I'll make a release soon, gotta just test another commit (unrelated) as well.

**Comment by tymondesigns** [comment]
Cool that dogfooding is possible haha

![image](https://user-images.githubusercontent.com/1801923/31843155-57a4189a-b5e9-11e7-847b-d821bef56142.png)

**Comment by fideloper** [comment]
Love it :D
