### ISSUE TITLE
Suggestion: Use xdebug.remote_connect_back setting

### ISSUE THREAD

**Issue by aanton** [shipping-docker/vessel#23]
First of all, thanks for this project!

I would like to share a suggestion. How about using `xdebug.remote_connect_back` instead of `xdebug.remote_host`?

This change would avoid setting the xdebug port. I think it's a good choice for development environments.

If you agree, I can work at the PR.

**Comment by fideloper** [comment]
I don’t think that works in context of docker in Mac or Windows (it may
work on Linux) due to the more complex networking setup used on those two
platforms (where there’s a layer of virtualization between docker and the
host machine).

If it does work, that’d be great (much simpler!) - do you happen to use
that yourself with docker to know?


Thanks!

**Comment by aanton** [comment]
I use `xdebug.remote_connect_back` in my local machine working on Linux (Ubuntu 16.04) with & without docker :)

I just tested it on a local virtual machine (boot2docker on VirtualBox) using docker-machine (to connect to the Docker daemon in boot2docker) and it works.

**Comment by fideloper** [comment]
I'll give it a test on Docker for Mac as well - hopefully it's as simple. I'm curious about what `$_SERVER['REMOTE_ADDR']` returns (I know I've checked but I don't remember). Thanks!

**Comment by fideloper** [comment]
(If I remember right, it'll be the Docker network's 172.*.*.* hostname which actually points to the VM that Docker runs inside of instead of a network on the Mac, which is why I end up pointing it to a specific IP address that *is* reachable from the container outside to the Mac host system).

**Comment by aanton** [comment]
Great. I'm waiting for your tests :)

In Ubuntu 16.04 + Virtual Box (boot2docker) + 2 containers (1 nginx:latest & 1 php:7-fpm) I get my machine IP (vboxnet0):

```bash
$ /sbin/ifconfig docker0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1
172.17.0.1

$ /sbin/ifconfig vboxnet0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1
192.168.99.1

$ docker-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
vm1    *        virtualbox   Running   tcp://192.168.99.101:2376           v17.10.0-ce   

$ docker-machine ip vm1
192.168.99.101

$ curl -s http://192.168.99.101/phpinfo.php | fgrep "\$_SERVER['REMOTE_ADDR']"                  
<tr><td class="e">$_SERVER['REMOTE_ADDR']</td><td class="v">192.168.99.1</td></tr>
```

**Comment by cringer** [comment]
I'll check in a Windows environment as I believe it is similar to the way Docker for Mac works.

**Comment by mfour-merickson** [comment]
@aanton Did you ever get xDebug working with Vessel?  I for the life of me cant make it work.  
@fideloper There must be something simple that I am missing (and I don't see any documentation for configuring xdebug)

**Comment by aanton** [comment]
@mfour-merickson yes, i did using `xdebug.remote_host` and `xdebug.remote_connect_back` separately. I do not remember if I had any problems or had to make any special configuration in phpstorm or in xdebug

**Comment by mikeerickson** [comment]
@aanton I got things working yesterday, all is good.  I am going to be creating a PR for the documentation so future users can have instructions.  One thing I am going to test is the information contained in this thread as well using `xdebug.remote_host` and `xdebug.remote_connect_back`

**Comment by aanton** [comment]
@mfour-merickson great!

**Comment by mikoop79** [comment]
> @aanton I got things working yesterday, all is good. I am going to be creating a PR for the documentation so future users can have instructions. One thing I am going to test is the information contained in this thread as well using `xdebug.remote_host` and `xdebug.remote_connect_back`

any luck with documentation?
