### ISSUE TITLE
When will windows ready?

### ISSUE THREAD

**Issue by stojankukrika** [shipping-docker/vessel#27]
Am rally try to make to docker works in windows but didn't find a way how to configure it in right way.. maybe this package make my life better :) Did you plain to release windows option for that and when?

**Comment by fideloper** [comment]
Hi!

You can keep track of #20 and #26 to see where Windows support is at.

Hopefully done soon! However there might be some special needs to get it running (e.g. "use this bash shell instead of that one")

**Comment by stojankukrika** [comment]
tnx @fideloper
