### ISSUE TITLE
Error on 4 step: usermod: UID '0' alredy

### ISSUE THREAD

**Issue by dka-develop** [shipping-docker/vessel#31]
OS: ubuntu 16.04.3 server amd64

Error: "usermod: UID '0' already 
After set:
RUN usermod -u 999 node
Instead:
RUN usermod -u $uid node

It's work.

**Comment by fideloper** [comment]
It looks like you’re running the build (or vessel start) as user root,
which isn’t an expected way to run Vessel.

Did you use sudo when running the vessel command? Are you running in Linux
as user root?

**Comment by dka-develop** [comment]
Yes. I used sudo for run vessel !
I will try without use sudo.

**Comment by dka-develop** [comment]
Working.
You were right.
Thank you.
