### ISSUE TITLE
Switch PHP Version

### ISSUE THREAD

**Issue by shiroamada** [shipping-docker/vessel#32]
Is there anyway I can switch PHP version for testing my project in different PHP version. 

2. How does the php.ini get updated?

**Comment by cringer** [comment]
There is not a way to switch the PHP version.  It uses the latest php version.  See #35 

If I'm not mistaken the php.ini is the default from the installation of the latest version of php.  There is no php.ini being specifically configured and copied in the Dockerfile so thats what I assume.

**Comment by fideloper** [comment]
Yep, this project will stay on the latest stable PHP. However, you can adjust the `Dockerfile` to install any PHP version that's available from the `ppa:ondrej/php` repository, which I believe is 5.6, 7.0, and 7.1.

There are a few ways to edit the php.ini:

1. Editing the `Dockerfile` to include (`COPY`) your own custom one
2. Using the `start-container` script to edit it on the fly whenever a new container is spun up

Last note: `php.ini` files are generally located at `/etc/php/7.1/fpm/php.ini` and `/etc/php/7.1/cli/php.ini`. The file path needs adjusting per version of PHP used.
