### ISSUE TITLE
Reasons against official PHP image?

### ISSUE THREAD

**Issue by zackify** [shipping-docker/vessel#35]
https://github.com/shipping-docker/vessel/blob/master/docker-files/docker/app/Dockerfile

Any reason to not use the base PHP image and install extra extensions after, this way changing versions is a little easier.

**Comment by fideloper** [comment]
Hi!

I use the Ubuntu base image as I found the official image harder to work
with to get all the modules and common software to use. The Ubuntu image
can get more people to contribute to the project, as it's familiar to more
people.

To keep things simple, this project will always use the latest stable
version of PHP as provided by the `ppa:ondrej/php` Ubuntu PHP repository.

**Comment by zackify** [comment]
Okay, thanks for the info! Awesome work on all of this :)

**Comment by fideloper** [comment]
Thanks!
