### ISSUE TITLE
Mapping an additional custom port

### ISSUE THREAD

**Issue by ashokgelal** [shipping-docker/vessel#36]
I'm trying to map a custom port (3000) under node container (I'm trying to see if I can make browsersync work). I've found no luck modifying `docker-compose.yml` to add:
```yml
    ports:
     - "3000:3000"
```

What would be the best way to map a new port?

**Comment by fideloper** [comment]
Hi!

Unlike the application, redis, and MySQL containers, the node container isn't one that is constantly running. It only starts up when doing doing a npm/yarn/node command (which in turn calls "docker-compose run --rm node <some command>"). Once the command finishes the container stops.

In your case, I would edit the "vessel" file and adjust the calls to node/npm/yarn and/or make a new Vessel command, which would look something like adding this:

```BASH
    # If "browse" is used, run npm
    # from our node container
    elif [ "$1" == "browse" ]; then
        shift 1
        $COMPOSE run --rm \
            -p 3000:3000 \
            node \
            npm "<WHATEVER COMMAND MAKES SENSE TO USE HERE $@>"
```

**Comment by ashokgelal** [comment]
Thanks! That did it for mapping the port but unfortunately couldn't figure out how to make the browsersync work with vessel.

**Comment by fideloper** [comment]
I’ve never figured that out either :/ (wasn’t sure if there was an official
way - I usually shut that feature off since it usually running in a VM or
Docker).

**Comment by ashokgelal** [comment]
I actually somehow got BrowserSync UI (at port 3001) working but never could proxy port 3000. I've been trying to convince my whole team to move forward with Vessel and this BrowserSync thing is the only blocker now from going all in. I'd invest more time to try to make it work but I lack enough Docker knowledge (even after watching your Docker series :)

**Comment by fideloper** [comment]
Let me know if you make progress! I think in the end here there's a fundamental issue of how BrowserSync works and can or cannot communicate to the host system. On Mac especially, there's a layer of virtualization between Docker and the MacOS system, which muddles things up.

Heres an image with a solution: https://github.com/ustwo/docker-browser-sync. Understanding it probably means digging into how browsersync works a bit.
