### ISSUE TITLE
Add `cron` package to App package

### ISSUE THREAD

**Issue by fideloper** [shipping-docker/vessel#37]
And document its usage within `vessel-docs` repository.

A few ideas on ways to run it:

1. Manual start: `./vessel run -d --rm app cron -f`
2. Via `docker-compose`, so it runs Laravel scheduler and optionally other stuff automatically (Mount a directory/file to cron.d perhaps)
3. Document adding it in during `ENTRYPOINT` script (`start-container`)

**Comment by knobik** [comment]
schedule should not be run on development. Vessel is DEV only env.
