### ISSUE TITLE
Permission issue running tinker

### ISSUE THREAD

**Issue by liefie** [shipping-docker/vessel#38]
## Description

How would I resolve this issue?

```
$ ./vessel art tinker

  [ErrorException]
  Writing to //.config/psysh is not allowed.
```

Which runs:
`docker-compose -f docker-compose.yml exec -u 501 app sh -c cd /var/www/html && php artisan tinker`

## OS

My OS is:

- [x] MacOS [High Sierra]
- [ ] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

The output of `docker-compose version`:

```
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by fideloper** [comment]
Hi!

I believe I've fixed this in our next release (2.0.0) via d1c71e6714ddc48bee1546d868c644e8a05c07d1. Until version 2.0.0 is out (it will be out today I think), you can test it out by deleting the package and re-requiring it directly from the `master` branch.

```bash
composer remove shipping-docker/vessel
composer require shipping-docker/vessel:dev-master
```

Note that 2.0.0 [requires re-building the images](https://vessel.shippingdocker.com/docs/updating-resetting/).

**Comment by fideloper** [comment]
(Re-open the issue if it still doesn't work. Im testing on a Linux machine shortly).

**Comment by liefie** [comment]
That's great it's working fine thanks.

**Comment by rokde** [comment]
Same behaviour on Ubuntu 16.04 with <2.0.0.

Works with 2.0.0 on Ubuntu 16.04

**Comment by fideloper** [comment]
Yep makes sense. Only 2.0.0 + will have this issue resolved.

Thanks
