### ISSUE TITLE
Ubuntu 17.10 issues

### ISSUE THREAD

**Issue by faasie** [shipping-docker/vessel#40]
## Description
A few issues:

./vessel {anything} throws `./vessel: line 21: /sbin/ifconfig: No such file or directory` since 17.10 doesn't use ifconfig anymore.

Image "hostnames" are not working. Inspecting the vessel network shows Names of _redis_1, etc. Documentation says hostnames are the service name. mysql doesn't work nor does mysql_1, etc. 
```
"Containers": {
            "2b4414631cb2350d086a893912379a1160f407e4d9659dee80f699105b262e87": {
                "Name": "financepackets_redis_1",
                "EndpointID": "947f8a6ca6d6ce3a7fe9a6bb10f7624bdae8cf474a75232d1cab6d1dc54ef9a6",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
```

./vessel art migrate (or any art/artisan) command doesn't run:
```
[ ~/Code/FinancePackets ] [ master | ✚5 ∞ ] ➜ ./vessel art migrate
./vessel: line 21: /sbin/ifconfig: No such file or directory
Execute a command in a running container

Usage: exec [options] SERVICE COMMAND [ARGS...]

Options:
    -d                Detached mode: Run command in the background.
    --privileged      Give extended privileges to the process.
    --user USER       Run the command as this user.
    -T                Disable pseudo-tty allocation. By default `docker-compose exec`
                      allocates a TTY.
    --index=index     index of the container if there are multiple
                      instances of a service [default: 1]
```
## OS

My OS is:

- [ ] MacOS [**Choose one:** Yosemite, El Capitan, Sierra, High Sierra]
- [X] Linux - Ubuntu 17.10
- [ ] Windows

## Docker

The output of `docker version`: 

```
Docker version 17.10.0-ce, build f4ffd25
```

The output of `docker-compose version`:

```
docker-compose version 1.8.0, build unknown
```

**Comment by faasie** [comment]
Nevermind. Ubuntu 17.10 is way too slow. Reverting back to OpenSuse.

**Comment by fideloper** [comment]
Thanks! I’ll make a note of that change for when we move on from 16.04.

**Comment by Sopamo** [comment]
I'm using 17.10 as well and installation & setup is fine for me. The application however is quite a lot slower than it is when running on homestead, but I'm not sure if that's because of vessel or because of my configuration :)
Anyhow, loving vessel so far, I'll post it here when I find out how to fix the slowness.

**Comment by fideloper** [comment]
It might be because of Docker on Mac/Windows - the file system integration
is slower unfortunately :/ (but let me know if you find something to help
you!)
