### ISSUE TITLE
unable to find user vessel

### ISSUE THREAD

**Issue by bryanrscott** [shipping-docker/vessel#41]
## Description
Version 2.0.  Note on a mac, so using the "I don't have PHP 7 yet" method.   Also note I comment out the install predis, and manually install using above method.

$ bash vessel init
VESSEL: Initializing Vessel...
VESSEL: Installing Predis
VESSEL: Setting .env Variables
VESSEL: Making vessel command available

VESSEL: Complete!
VESSEL: You can now use Vessel
VESSEL: Try starting it:
./vessel start
$ ./vessel start
Creating rimf2_pgsql_1 ... 
Creating rimf2_node_1 ... 
Creating rimf2_redis_1 ... 
Creating rimf2_app_1 ... 
Creating rimf2_pgsql_1
Creating rimf2_redis_1
Creating rimf2_node_1
Creating rimf2_app_1 ... done
it-042015:rimf2 bryanscott$ ./vessel composer outdated
unable to find user vessel: no matching entries in passwd file

## OS
My OS is:
- [ X] MacOS [High Sierra]

## Docker

The output of `docker version`: 

it-042015:dist bryanscott$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

The output of `docker-compose version`:

docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

**Comment by bryanrscott** [comment]
I can manually add a user
useradd -d /var/www/html -G www-data -u 501 vessel

But the ./vessel commands are being issued in / . eg
$ ./vessel composer outdated
Composer could not find a composer.json file in /
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

**Comment by bryanrscott** [comment]
Have dropped back to 1.1 for now.

**Comment by fideloper** [comment]
Hello! 
When upgrading, did you rebulid your containers (info and links to docs here: https://github.com/shipping-docker/vessel/releases/tag/2.0.0 )? That step to add user Vessel is completed after a rebuild on step 2.

**Comment by bryanrscott** [comment]
I am using the catch-22 instructions and clear before starting.
The mod I do to the instructions is I add
docker run --rm -it \
    -v $(pwd):/opt \
    -w /opt shippingdocker/php-composer:latest \
    composer require predis/predis

and comment out from the vessel command.   

Additionally even though I run the command to publish assets I find it does nothing, but reports no errors.   So I manually copy docker-files directory.

**Comment by fideloper** [comment]
Hello!

When you say you "clear before starting", does that mean you delete your `vessel/app` image and rebuild it?

See **Step 4** under [Updating Vessel](https://vessel.shippingdocker.com/docs/updating-resetting/) to see what I mean there.

**Comment by bryanrscott** [comment]
No I did not do that step.  I skipped as it said optional.    I will try the upgrade again tonight so I have more bandwidth.

**Comment by bryanrscott** [comment]
I got further doing step 4.    But now I seem to lose network connection to the containers.   rolling back and staying with 1.1 for now.
