### ISSUE TITLE
Postgresql Support

### ISSUE THREAD

**Issue by bryanrscott** [shipping-docker/vessel#43]
Would it be possible to include the PG_PORT in the vessel script and include a pgsql dir in docker?  
 It would make supporting postgresql so much simpler, and not have a detrimental impact on mysql ie

export APP_PORT=${APP_PORT:-80}
export MYSQL_PORT=${MYSQL_PORT:-3306}
**export PGSQL_PORT=${PGSQL_PORT:-5432}**
export WWWUSER=${WWWUSER:-$UID}

**Comment by fideloper** [comment]
Hello!

I see what you mean, but I'm not sure I see the overall benefit of adding a
(mostly unused) port. If people are going to customize the
docker-compose.yml file, they might as well also edit the vessel file.

I don't think I'll pull this in, but in the docs on using pgsql over mysql,
I'll include that change to the vessel file that people can do.

Thanks!
