### ISSUE TITLE
Error in building node when running ./vessel start

### ISSUE THREAD

**Issue by andytan2624** [shipping-docker/vessel#44]
## Description

When I try to run vessel start, I get this error. Do you know what I can do to fix it

```
Andys-MacBook-Pro:calibrate_new ash_skywalker10$ ./vessel start
Creating network "calibratenew_vessel" with driver "bridge"
Creating volume "calibratenew_vesselredis" with local driver
Creating volume "calibratenew_vesselmysql" with local driver
Building node
Step 1/6 : FROM node:latest
ERROR: Service 'node' failed to build: Get https://registry-1.docker.io/v2/library/node/manifests/latest: unauthorized: incorrect username or password
```

## OS

My OS is:

- [ x] MacOS [Sierra]
- [ ] Linux
- [ ] Windows
## Docker

The output of `docker version`: 

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

The output of `docker-compose version`:

```
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by fideloper** [comment]
That’s interesting - error is coming from docker’s official repository. I
wonder if there’s an error on their end. That repository doesn’t require
authentication to pull images from (or shouldn’t!)

Have you tried again later to see if that error cleared up?

**Comment by fideloper** [comment]
I get that error following the link in my browser. However I think it’s
temporary in any case.

Ok your Mac, try running “docker pull node:latest” and see if you get there
error there as well.

**Comment by andytan2624** [comment]
Hi Chris

I've run docker pull node:latest on my command line and the error is still the same unfortunately

**Comment by fideloper** [comment]
Gotcha - so the issue isn't specific to Vessel. I can load in the latest node image manually as well:
![image](https://user-images.githubusercontent.com/467411/33019063-810471c0-cdbe-11e7-88d5-2e22d43b861a.png)

I'm thinking restarting Docker or your computer might help! Otherwise I'm out of ideas! Maybe create a user at hub.docker.com and log into your Docker instance with it. I guess technically I'm logged in on my machine:

http://drop.userscape.com/oF0Z9U/4dG5Hx0Z

**Comment by andytan2624** [comment]
Just resolved my issue, I just had to run docker logout on my terminal window, and then i could pull in the latest node image which I probably should have done this from the beginning

Thanks again for your help Chris :)

**Comment by fideloper** [comment]
Ah ha, great! You're welcome!
