### ISSUE TITLE
Add secondary (frontend) app container [feature]

### ISSUE THREAD

**Issue by tobz-nz** [shipping-docker/vessel#46]
## Description
More apps these days are separating api & frontend. It'd be great to have this this setup with Vessel.

I'm new to docker so probably not sure how to set this up myself

**Comment by fideloper** [comment]
Might make sense if you have two code bases as well!
Check out the https://vessel.shippingdocker.com/docs/learn-more/ free courses, they'll hopefully give you a good idea of how to use Docker in a way that'll let you add that to your project.

It's not something I want to add to Vessel as a default, however.
