### ISSUE TITLE
Request for info: inject some custom tasks into container building

### ISSUE THREAD

**Issue by mityukov** [shipping-docker/vessel#49]
## Description

Hi, I'd like to make it as easy as possibly for other developer to spin up a local copy of our system. For this, I'm going to have vessel installed, listed in my composer.json/.lock files, `vendor:publish`ed on the dev installation. Then I would  provide some basic instructions, like these:
```
git clone myRepoURL && cd myRepo
composer install
bash vessel init
./vessel start
./vessel artisan migrate
./vessel yarn install
./vessel yarn run dev
```
(composer and docker would be pre-requirements, off cause; is anything else required o the dev's computer, by the way?)

I would only need few extra things to be executed right after container is started, but before running migrations. Something like:
- creating database tables (old ones, whey existed before I started using Laravel with its migrations, so, they're "off track")
- downloading some demo data to start with.

My understanding is that the right place for these "one-off hooks" would be during the `bash vessel init` step. But I need those scripts to be in my version control and that vessel find them there and execute automatically. Is anything like this supported?

## OS

My OS is: MacOS High Sierra

Developer's OS is: probably Windows. But it could be anything, in fact…

**Comment by fideloper** [comment]
Nothing is there for that out of the box, you can certainly set that up, likely by adding to the Vessel file itself. If you want to run all executable scripts within a directory, you can likely use `run-parts`: https://askubuntu.com/questions/622038/how-to-execute-all-scripts-in-a-path
