### ISSUE TITLE
How to connect to MySQL Database using Sequel Pro

### ISSUE THREAD

**Issue by mfour-merickson** [shipping-docker/vessel#50]
Trying to connect to the database using Sequel Pro but not having much success?  Any chance you have the secret?

## OS

My OS is:

- [x] MacOS [Sierra]
- [ ] Windows

## Docker

The output of `docker version`: 

```
17.09.1-ce
```

The output of `docker-compose version`:

```
1.17.1, build 6d101fb
```

**Comment by fideloper** [comment]
Here you go:
https://vessel.shippingdocker.com/docs/everyday-usage/#sequel-pro

**Comment by mikeerickson** [comment]
Thanks, call it a stupid pilot error.  Forgot to remap default port (3306) as it was already in use my local install.  Mapped to 33061 and all is groovy
