### ISSUE TITLE
Crashing on mac os sierra

### ISSUE THREAD

**Issue by ankurk91** [shipping-docker/vessel#51]
## Description
> Docker is crashing the whole OS

`bash vessel init` command runs fine.
`./vessel start` command starts then crashed whole OS at `Step 6/17`
(this is happening every time, i have tried 3 times today)
See terminal output (link below).

After crash; computer restart automatically and docker prompt with this screen.
![docker-crash](https://user-images.githubusercontent.com/6111524/34520442-a5470a6c-f0ae-11e7-9a2b-60dc3f951b16.jpg)
I clicked "Reset" and the docker service runs fine.

## OS

My OS is:
* MacOS [Sierra v10.12.3] Core i5, 8GB

## Docker

The output of `docker version`: 

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

The output of `docker-compose version`:

```
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

### Additional info
* Docker was installed through brew
```
brew cask install docker
```
* System already has apache 2.4, php 7.1 and mysql 5.7 installed, running on default ports.
* `.env` contents
```
# Added after default Laravel env variables
APP_PORT=9090
MYSQL_PORT=33060
```
* Here is the full terminal output
https://gist.github.com/anonymous/4b70ab341b4f2a531cda63beb58b0caa
* System had enough RAM available to operate

Thanks.

**Comment by fideloper** [comment]
Not sure I can do anything about this. I've never installed it via Brew, perhaps that changes something. Is it just and only with Vessel?

Theo output doesn't really show any error, it seems to just stop in middle of an `apt-get update`.

The system can have enough RAM, but Docker itself has limits set too:

![image](https://user-images.githubusercontent.com/467411/34521792-3d3e1a54-f055-11e7-8150-f7bd7245f84b.png)
