### ISSUE TITLE
How to configure xDebug w/ PHPStorm

### ISSUE THREAD

**Issue by mfour-merickson** [shipping-docker/vessel#54]
## Description

I have been trying to figure out all day how to get xDebug configured with Vessel and am not have any success at all.  Does ANYBODY know the trick to making this work?

## OS

My OS is:

- [x] MacOS  Sierra, High Sierra

## Docker

The output of `docker version`: 

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

The output of `docker-compose version`:

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by mfour-merickson** [comment]
Here is my 20-xdebug.ini info inside container

```
root@4ab8afe0df4b:/etc/php/7.1/cli/conf.d# cat 20-xdebug.ini
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
xdebug.idekey=docker
xdebug.remote_host=localhost:8282
```

**Comment by mfour-merickson** [comment]
@fideloper Good news, just figured it out.  I am going to write up instructions and would be happy to submit a PR to the documentation for future users if you would like.

**Comment by 4mation** [comment]
Hi @mfour-merickson 

I'm currently encountering this issue at the moment, would you be able to let me know what you to fix it on your end?

**Comment by andytan2624** [comment]
Hey @mfour-merickson or @fideloper 

Like 4mation I'm currently having issues with setting up xdebug and vessel, was there any PR for this branch on how to configure xdebug for phpstorm and vessel cause I'm running into issues and wanted to know how you were able to get it done

Cheers,
Andy

**Comment by mikeerickson** [comment]
Sorry, never got around to writing it up. I will complete this task tomorrow

@andytan2624

**Comment by andytan2624** [comment]
Hi @mikeerickson 

Thanks for that, much appreciated :)

**Comment by mfour-merickson** [comment]
@andytan2624 Finally got around to writing this up.  If you want to have a run with this information before I submit final PR, I would appreciate it.  Please let me know what issues you may run into, or that is not clear enough.

@fideloper If you have a free minute, have a look at this information and let me know what possible changes you would like added before I submit a PR to the repo instructions

[xDEBUG.md.zip](https://github.com/shipping-docker/vessel/files/1813153/xDEBUG.md.zip)

**Comment by andytan2624** [comment]
Hi @mfour-merickson 

Thanks for writing that, just had a couple things to clarify because I can't get it working on my end :( 

- Do i need to have xdebug helper installed and turned on in my browser or that's not needed?
- Do i need to have XDEBUG_HOST or WWWHOST set up in .env file for this to work?
- Is the path mapping I got here correct?
<img width="1234" alt="screen shot 2018-03-16 at 6 43 39 am" src="https://user-images.githubusercontent.com/5368849/37487420-99a42838-28e5-11e8-885d-1e03a3c508f1.png">

Thanks again for your help on this

Cheers,
Andy

**Comment by mikeerickson** [comment]
Helper is not required (if it is installed and active, you must disable or it will interfere)

Path mapping looks correct to me

The XDEBUG_HOST and WWWUSER variables are populated by Vessel application when using `start`

**Comment by mikeerickson** [comment]
What OS are you using 
Which version of Vessel are you using

**Comment by andytan2624** [comment]
Currently using version  2.1.0 for vessel

OS is Mac

I've tried this with the listening for PHP Debug connections on and off in PHPStorm

**Comment by mfour-merickson** [comment]
Run the following and see if the XDEBUG_HOST variable is indeed defined

```bash
docker-compose exec container env
```

or 

```bash
docker-compose exec app bash -c 'echo "$XDEBUG_HOST"'
```

**Comment by mfour-merickson** [comment]
I am not sure if this makes much of a difference, but I am using `vessel` 3.0.1 (latest dev, master)

**Comment by andytan2624** [comment]
When i run those commands, the value I get is

XDEBUG_HOST=192.168.0.10

**Comment by andytan2624** [comment]
Yeah perhaps i might need to upgrade vessel on my local then if there's no other option

**Comment by mfour-merickson** [comment]
OK, so you know the `XDEBUG_HOST` is correct, we are close.

When you attempt to degug, what happens?

**Comment by mfour-merickson** [comment]
@andytan2624 OK, I think I forgot to define some additional configuration. Can you please do the following:

```bash
./vessel exec app bash
cd /etc/php/7.1/mods-available
vi xdebug.ini
```

and show me what you have here

**Comment by andytan2624** [comment]
Hey

So this is inside my xdebug.ini

```
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
xdebug.idekey=docker
xdebug.remote_host=192.168.8.178
xdebug.max_nesting_level = 500
```

Do I have to update the xdebug.ini file in docker folder?

**Comment by mfour-merickson** [comment]
OK, one small change

```
xdebug.remote_host=192.168.8.178
```

should be

```
xdebug.remote_host=192.168.0.10
```

You may need to restart the container

```
./vessel stop && ./vessel start
```

**Comment by andytan2624** [comment]
i thought that would do it, but it didn't work unfortunately and it doesn't break at the break point I set up. I updated the remote host value in docker/app/xdebug.ini 

I might have to update vessel perhaps then

**Comment by mikeerickson** [comment]
You should be editing the xDebug.ini file for the version of php you are using 

```
cd etc/php/7.1/mods-available/xdebug.ini
```

**Comment by mikeerickson** [comment]
If the above change doesn’t help, then I would recommend upgrading Vessel version.  

I don’t know if that is a requirement, but it seems to be the only other difference

**Comment by mfour-merickson** [comment]
@andytan2624 So, it seems that xDebug is creating the container when you start

So, all the edits to `xdebug.ini` are NOT required, they are managed by `vessel` internally when the environment is started using `./vessel start`

**Comment by andytan2624** [comment]
@mfour-merickson Yeah cause everytime I run `./vessel stop` and then `./vessel start` , it'll undo the changes i made in xdebug.ini in bash

So the remote_host in your xdebug.ini file matches the value of XDEBUG_HOST for you?

Haven't updated vessel yet, will do in about an hour when I get a break from work :)

**Comment by mfour-merickson** [comment]
@andytan2624 Yes it does!

**Comment by mfour-merickson** [comment]
@andytan2624 Any luck getting things working? I am pretty curious as to what your issue is/was I have had some colleagues try out the workflow and we are all able to debug.

**Comment by andytan2624** [comment]
Hey @mfour-merickson 

No luck. I've upgraded vessel to 3.0.1 and I upgraded docker on my mac

I've updated my /docker/app/xdebug.ini xdebug.remote_host value to 192.168.0.10 and ran `bash vessel init`, so when I checked xdebug.ini in /etc/php/7.1/mods_available/xdebug.ini, it also had the same remote_host

I 've also attached screenshots of my set up

It just won't debug for me unfortunately, I don't think I can get this to work for me

<img width="1246" alt="screen shot 2018-03-17 at 8 34 57 am" src="https://user-images.githubusercontent.com/5368849/37545784-55b25508-29be-11e8-87ff-6f6e22ff4809.png">

<img width="1066" alt="screen shot 2018-03-17 at 8 35 05 am" src="https://user-images.githubusercontent.com/5368849/37545792-590226ac-29be-11e8-919d-8263e6163956.png">

<img width="1438" alt="screen shot 2018-03-17 at 8 35 55 am" src="https://user-images.githubusercontent.com/5368849/37545800-5f87c1b2-29be-11e8-8081-e5f21b38084b.png">

**Comment by mikeerickson** [comment]
Sure looks like you have it all configured correct.  The only thing I have to do different is when I am working from office network (not Wifi) I have to restart vessel session (to update the `xdebug.remote_host` with correct IP address)

```
./vessel stop
./vessel start
```

**Comment by andytan2624** [comment]
Yeah didn't work for me, I'm going to try this on my windows computer and see if that works there as opposed to a mac

**Comment by mfour-merickson** [comment]
Sorry to hear that, really curious as to what is causing the issue.

**Comment by harrygulliford** [comment]
For VS Code users,
1. Add `XDEBUG_HOST=0.0.0.0` (with your current ip address) to your projects `.env` file.
2. Open your `launch.json` VS Code settings and add the following:
```
"pathMappings": {
    "/var/www/html": "${workspaceRoot}"
}
```
(No need to change the port number from 9000, even if your app is running on something different)
