### ISSUE TITLE
Documentation instructions about MySQL will not work

### ISSUE THREAD

**Issue by maaxxicarvalho** [shipping-docker/vessel#55]
## Description
I was trying to execute the command to [import a SQL file into the database](https://vessel.shippingdocker.com/docs/everyday-usage/#mysql) but it's not working.

Apparently, when calling `< /opt/example.sql`, the command points to the local directory, so something like the command below works but not as you wrote in the documentation.

```bash
./vessel run --entrypoint "" --rm mysql mysql -h mysql -u root -psecret any_database < import.sql
```

## OS

My OS is:

- MacOS High Sierra

## Docker

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by marcusmyers** [comment]
@maaxxicarvalho You shouldn't to worry about the `--entrypoint`, but you could try the following in place of the docs:

```
./vessel run --rm \
    -v exports:/opt \
    mysql sh -c \
    'mysql -h mysql -u root -p example < /opt/example.sql'
```

**Comment by fideloper** [comment]
Thanks, I'll update the docs! Using `sh -c "FULL CMD HERE"` is definitely the way to go. 

`--entrypoint` shouldn't be needed as the entrypoint script used passes-through any commands when given.
