### ISSUE TITLE
Running Vessel in continuous integration

### ISSUE THREAD

**Issue by michielgerritsen** [shipping-docker/vessel#62]
Thanks for Vessel, it's a great tool. I have noticed that it has a lot of similarities with the code from the Shipping Docker course. Only the CI part is missing, mainly the TTY switch (-T). Is this intentional? When i create a pull request adding this, would it be accepted?

**Comment by fideloper** [comment]
Hi!

Right - this (the core project) is meant more for development, but it could definitely be adjusted to work in a CI environment. I think the specifics of those changes would depend a great deal on the tools used for CI however, so I don't think I can necessarily support that use case.

In fact, the TTY switch from the course might be specific to using it in Jenkins (although I'm not really sure - perhaps that's a similarity amongst any CI tool that lets you use your own containers).

For now I think I'd skip it. Maybe its something that can be documented, like a section on "using Vessel in jenkins"
