### ISSUE TITLE
How to have to vessel containers talking to each other i.e. a frontend and an api backend

### ISSUE THREAD

**Issue by andytan2624** [shipping-docker/vessel#64]
## Description
I know this was asked by someone if this could be a feature as Vessel before, but does anyone know what adjustments I need to do to have one vessel container be able to call a url belonging in a different vessel container like a frontend and a backend

When I do this, I keep getting "Failed to connect to localhost port 8080: Connection refused" when my frontend vessel (which is located at localhost:8090) trying to call a url at my API vessel (located at localhost:8080)

I assumed that because they were under the same network, it should work. Any help would be greatly appreciated

Please

## OS

My OS is:

- [ x] MacOS [High Sierra]
- [ ] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

```

The output of `docker-compose version`:

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by fideloper** [comment]
Any docker container within the same Docker network (as docker containers are here in vessel) can talk to eachother. The name of the container becomes the hostname.

Note that port 8080 is likely the port forwarded between your host machine and the docker container. If your service isn't listening on port 8080 within the container (it sounds like it is not) then your internal HTTP requests should use the port being used in the container, which is likely port 80.

Definitely watch the "Docker in Development" course [linked to from the docs here](https://vessel.shippingdocker.com/docs/learn-more/) to learn some more on how that's put together.

**Comment by fideloper** [comment]
Actually the hostname to use to reach the container is simpler - it's the name of the docker compose service, so use hostname `app:80` to reach the app container on port 80 (instead of the container name, which can change).

**Comment by andytan2624** [comment]
Hi @fideloper 

thanks for the reply. I tried using app:80 so I used it like below from my frontend container

` \Httpful\Request::get('http://app:80/api/test')`

To call a api url from my api container, however its only looking for a url in the frontend container only. So I guess this will require me to rename the docker compose service 'app' in the backend container to a different name to like 'app2'. Then I'm guessing 
 \Httpful\Request::get('http://app2:80/api/test')` would work then

**Comment by fideloper** [comment]
That sounds right! Is the API container in the same docker compose setup?
If not, it might be some extra work to get the containers all in a common
docker network.

**Comment by andytan2624** [comment]
Oh nah, I have separate docker compose setup for my frontend and api container cause i thought that'd be the better way to go about it

ahh i thought it'd be the same docker network since they share the same network name in each docker-compose file

**Comment by fideloper** [comment]
Gotcha! Right - docker compose will create different networks with slightly different names in that case. However you can tell it to join a network you make manually (tell it to join a network without trying to create it).

See here on that: https://docs.docker.com/compose/networking/#use-a-pre-existing-network

**Comment by andytan2624** [comment]
Thanks for the tip, that works well =) . After trying for a while, I did the following to make it work

- In the api container, renamed the app service in docker compose file to api_app
- In the frontend container, I put the following under the app service
```   
    external_links:
          - < name of api container >
    networks:
          - default
          - <name of api network (use docker network ls)>
```
- Down below the frontend container, underneath the network section of docker compose file, I have this
```
networks:
  vessel:
    driver: "bridge"
  <name of api network>:
    external: true
```

And now I'm able to make API calls from the frontend container to the api container using http://<name of api container>:80

**Comment by fideloper** [comment]
Great!
