### ISSUE TITLE
Latest tagged version is currently broken (3.0.0)

### ISSUE THREAD

**Issue by dbpolito** [shipping-docker/vessel#65]
You probably know that, but you need to tag a new version. Just a reminder ❤️ 

This might scare new comers.

Master branch is working just fine. (https://github.com/shipping-docker/vessel/commit/d8e041ce1b14797c927668bcc83ae94cf85f3c7e)

**Comment by michgeek** [comment]
Thanks for the info!

**Comment by fideloper** [comment]
whoops, sorry! fixing that up

**Comment by fideloper** [comment]
Done! Tagged 3.0.1
