### ISSUE TITLE
Help Wanted label?

### ISSUE THREAD

**Issue by benfreke** [shipping-docker/vessel#67]
Hi

Love this idea. I've been doing similar stuff myself, so I'm happy to abandon that and use this instead. Have you considered using the "Help Wanted" label to allow people like myself to contribute fixes?

Also, the images. You're using "latest" in a lot of cases, building containers locally rather than pushing them to the docker hub and not using alpine images. Are those future enhancements or are they simply not needed? I imagine there are some "gotchas" there too :) 

Really looking forward to trying this out, I wasn't too keen on getting xdebug working :)

p.s. Sorry if making this an issue is the wrong format, I couldn't see any other contact options.

**Comment by fideloper** [comment]
No worries!

I do use `ubuntu` on purpose, as it's easier to work with in a community that's not super familiar with Docker and the "extra work" needed to figure things out on Alpine (I'd like to keep it that way for now!).

I also have the workflow of building containers locally on purpose for now as well - there are a LOT of gotchas and small things that need adjusting depending on the user's local system ('Nix vs MacOS vs Windows) that need to be taken into account so file sharing works properly for local dev, and some of them are accounted for at build-time.

In any case, a Help Wanted tag is a great idea, I'll make that label.
