### ISSUE TITLE
Comparison with others vs valet and homestead

### ISSUE THREAD

**Issue by jericopulvera** [shipping-docker/vessel#7]
Anyone can add a comparison of vessel with others such as Valet and Homestead?

Thanks.

**Comment by cringer** [comment]
There is no comparison.  They are all different technologies.  Vessel is using Docker.

I don't see how it's the package maintainer responsibility to tell you the difference between the technologies.  

https://laravel.com/docs/5.5/valet
https://laravel.com/docs/5.5/homestead

**Comment by jericopulvera** [comment]
Oh ok thanks.

**Comment by fideloper** [comment]
Here's some basic info related to that:

1. Homestead is a full virtual machine (a little server running inside your main computer). It's potentially a bit heavy in terms of CPU/RAM usage, but it's the most like running stuff inside of a "real" server
2. Valet installs PHP, Caddy, MySQL and I believe Redis (?) on your mac directly. It's the least like a real server environment, but it's the fastest way to run your code as it's just software running directly on your Mac (Valet is Mac-only)
3. Vessel is sort of an in-between. It's not a full VM (although on Mac it has to run in  a small layer of virtualization, so there is a small VM running), and containers generally only use what CPU/RAM they need.  It's based on Docker as mentioned. It can run processes such as MySQL, php-fpm, Nginx, (etc) within it's own little world ("container")  that uses some of the stuff from the host system but also still sectioned off from the host system.
