### ISSUE TITLE
No project in /var/www/htlm

### ISSUE THREAD

**Issue by cloudbluedigital** [shipping-docker/vessel#75]
Hi

My problem is that I run ./vessel start and everything has been started however my app container and /var/www/html folder is empty like my project is not binded. Is there any way to fix this?

**Comment by fideloper** [comment]
Please fill out the form given/shown when making a new issue. That'll help because I don't have enough info to guess what might be going wrong. 

One thing would just be to stop the project and restart it to see if that helps.

**Comment by sergeifilippov** [comment]
Possible typo? `/var/www/html` vs `/var/www/htlm`

**Comment by fideloper** [comment]
looks like it! is that in the docker-compose file? or perhaps the “vessel”
file.
