### ISSUE TITLE
Add Apache Support

### ISSUE THREAD

**Issue by mikeerickson** [shipping-docker/vessel#78]
Looking to see if anybody has extended this project to use Apache instead of nginx

## OS

My OS is:

- [X ] MacOS [Sierra]
- [ ] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

N/a

**Comment by fideloper** [comment]
I'm keeping this project as simple as possible and not extending it to add extra tech

**Comment by fideloper** [comment]
Right on! (I've had other projects blow up on me and need a ton of extra support time when I added too many extra features - trying really hard to keep it simple this time!)
