### ISSUE TITLE
Vessel ignores APP_PORT and MYSQL_PORT in .env file

### ISSUE THREAD

**Issue by shealan** [shipping-docker/vessel#8]
Fantastic little package. Only issue I have encountered so far is the fact I can't seem to get it to recognise the `APP_PORT` and `MYSQL_PORT` variables stored in my env file.

I can start Vessel using those ports by defining them in the command line before start, but in the env file they seem to be ignored. I have tried to destroy all volumes, images and containers and essentially start from scratch but with the same result.

**Comment by nickknissen** [comment]
What does your `.env.vessel ` look like?

**Comment by fideloper** [comment]
Hi!

You're hitting a bug that's fixed but not in the latest release yet.

APP_PORT and MYSQL_PORT should be defined in the CLI for now. I have a
commit in place that makes it possible to use those in your .env file, but
it's not released yet. (i'll test that out and release it soonish)

Side note tho: .env.vessel is just a backup of the original .env before
it's changed a bit by Vessel. The .env file is what's read by both Laravel
and Vessel.

**Comment by shealan** [comment]
Thanks for the update and all your hard work @fideloper 🤘🏼

**Comment by fideloper** [comment]
Fixed in e18cbaaa714b77f1ad2fabbddea8006e8c95e662
