### ISSUE TITLE
Getting %1 is not a valid Win32-application. (error 0xc1) when running commands that require an interactive shell

### ISSUE THREAD

**Issue by AnwarElbo** [shipping-docker/vessel#84]
## Description
I have succesfully installed vessel on my windows 10 machine using git bash. Now I get an error whenever I use a command which requires an interactive shell. So when I ran `./vessel art migrate` I get this error `the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'`. So I did what the error tells me and ran `winpty ./vessel art migrate` and here I get the error `winpty: error: cannot start 'D:/code/multisocial/vessel art migrate': %1 is not a valid Win32-application. (error 0xc1)`.  
I hope this explains it well enough, any tips or work arounds will be appreciated. A possible fix is making the interactive shell optional with some kind of argument.

## OS

My OS is:

- [ ] MacOS [**Choose one:** Yosemite, El Capitan, Sierra, High Sierra]
- [ ] Linux
- [x] Windows

## Docker

The output of `docker version`: 

```Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

The output of `docker-compose version`:

```
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Comment by michaeljstutz** [comment]
Just had the same issue happen, my fix was to modify the vessel script at line 56.

Before: 
```
# Create base docker-compose command to run
COMPOSE="docker-compose"
```

After:
```
# Create base docker-compose command to run
if [ "$MACHINE" == "mingw64" ]; then
    COMPOSE="winpty docker-compose"
else
    COMPOSE="docker-compose"
fi
```

Might not be the correct way around the issue but it worked for me.
