### ISSUE TITLE
Unable to locate packages php7.2-memcached and php7.2-xdebug

### ISSUE THREAD

**Issue by gabrielboliveira** [shipping-docker/vessel#86]
## Description
When rebuilding images, the `apt-get install` command from `app` container fails with a `Unable to locate package` error.

![image](https://user-images.githubusercontent.com/11093090/46954575-5751fd00-d067-11e8-87b5-230103629cf0.png)

## OS

My OS is:

- [X] MacOS Mojave (10.14)

## Docker

The output of `docker version`: 

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

The output of `docker-compose version`:

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Comment by gabrielboliveira** [comment]
Looks like the issue is on ondrej PPA repo. 

There's another bug happening: php 7.3 cli is also installed, and composer, artisan and all command line scripts uses the 7.3 version. So for example, `artisan migrate` will result in a `could not find driver` exception, because the mysql extension is not installed for 7.3.

Lots of issues related to these errors on https://github.com/oerdnj/deb.sury.org/issues.

**Comment by fideloper** [comment]
Hmmm gross, sorry about the trouble! What happens if you exclude the `xdebug` package, and then change memcached to just `php-memcached` ?

Otherwise I have a feeling the real solution will be to wait for the PPA to get fixed and to get running now, you'll have to exclude those two packages.

**Comment by gabrielboliveira** [comment]
Removing `php7.2-memcached` and `php7.2-xdebug` from the install fixes the container build problem. 

The other one, related to 7.3 cli version, it's solved removing `php-msgpack` and `php-igbinary`. Looks like these two packages are now downloading php7.3 by default

**Comment by fideloper** [comment]
Ooph hope the PPA gets cleared up soon!

**Comment by fideloper** [comment]
I got an email (via Patreon update) from the maintainer of the PPA (Ondrej), he said those fixes should be resolved if you want to try re-building this image.

The "resetting" docs will tell you how if you're not familiar with the process: https://vessel.shippingdocker.com/docs/updating-resetting/#resetting

**Comment by gabrielboliveira** [comment]
Side note: regarding the "resetting" docs, I have another solution for that: 

I run `./vessel build --pull --no-cache` so it rebuilds everything pulling fresh version from Hub.

Not sure tho if it's totally the same thing as you do on the docs.

**Comment by fideloper** [comment]
Ah, thanks!

**Comment by mikeerickson** [comment]
I need to spin up a new project later this week and was planning to use Vessel.  Is this something I should watch out for, or will it work as is? I don’t want to use PHP 7.3 (Want to use 7.2)

**Comment by fideloper** [comment]
It looks like php7.2 should work fine with this update. I'll get a release out right now so when you install it again, it'll grab these latest files.

**Comment by gabrielboliveira** [comment]
All should work OOB. I've tested on a Laravel 5.6 project with this new update, and everything worked flawlessly. Composer, artisan, fpm, working great.

**Comment by mikeerickson** [comment]
@fideloper thanks bud, greatly appreciate it.
