### ISSUE TITLE
Nginx fallback for .js files not working.

### ISSUE THREAD

**Issue by fkraefft** [shipping-docker/vessel#93]
## Description

I'm trying to return a url with .js extension with a dynamic file from laravel.

The file is return because nginx return index.php as a 404 fallback response in the default nginx config file.

`error_page 404 /index.php;`

But I want the request to be return in the normal location in order to receive a 200 response from laravel.

`location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }`

## OS

My OS is:

- [Mojave]

**Comment by fideloper** [comment]
Hi!

I've had to do this before as well - 

Inside of the [`default`](https://github.com/shipping-docker/vessel/blob/master/docker-files/docker/app/default) configuration file for Nginx, add the following above `include h5bp/basic.conf;`:

```
    # This must be before inclusion of h5bp
    location ~* ^/s/(.*)/survey\.js$ {
        fastcgi_index index.php;
        include fastcgi.conf;
        fastcgi_param  SCRIPT_FILENAME    $document_root/index.php;
        fastcgi_param  SCRIPT_NAME        index.php;
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
    }
```

Note that the file path I have there in the `location` block is specific to my application. You'll need to adjust it for yours.

After that change, you'll need to [rebuild your `vessel` Docker image](https://vessel.shippingdocker.com/docs/updating-resetting/) for the project:

```bash
# Try this first
./vessel build app

# If it doesn't rebuild - shows the image is up to date, run this:
docker image rm vessel/app
./vessel build app
```

**Comment by fideloper** [comment]
LMK if you hit issues. note that I'll likely leave the core project as-is, rather than make this a standard use case.
